### PR TITLE
Fix memory management in CmdLineArgs

### LINKED ISSUE #65: Properly fix `CmdLineArgs` memory leak
#63 was incomplete. It fixed the double memory release, but not the leak.

The `argv()` call should return a copy of the array, so that benchmark may modify as it wants to.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #65. We just need a copy for `_argv` and delete its entries instead.
Furthermore, we can use a range-based for loop.

### CODE REVIEW

**Comment by aprokop** [comment]
Better fix than #63

File: examples/bvh_driver/bvh_driver.cpp [hunk 1]
```diff
@@ -267,21 +274,17 @@ class CmdLineArgs
...
-    // _argc values is garbage, and would have been already released.
-    for (int i = 0; i < _argc; ++i)
+    for (auto const &p : _argv_copy)
     {
-      delete[] _argv[i];
+      delete[] p;
     }
   }
+
   int &argc() { return _argc; }
```
Comment (dalg24) [inline examples/bvh_driver/bvh_driver.cpp]: I guess we should add an empty line here too while you are at it

File: examples/bvh_driver/bvh_driver.cpp [hunk 2]
```diff
@@ -267,21 +274,17 @@ class CmdLineArgs
...
   ~CmdLineArgs()
   {
-    // Benchmark removes its own arguments from the command line arguments.
-    // This means, that by virtue of returning references to internal data
-    // members in argc() and argv() function, it will necessarily modify the
-    // members. It will decrease _argc, and "reduce" _argv data. This, however,
-    // will result in _argv having the original size, but the data beyond first
-    // _argc values is garbage, and would have been already released.
-    for (int i = 0; i < _argc; ++i)
+    for (auto const &p : _argv_copy)
```
Comment (dalg24) [inline examples/bvh_driver/bvh_driver.cpp]: Reference was unnecessary in the 1st place.  I find the `const` qualifier disturbing.
