### PR TITLE
Disable manufactured solution tree query test for SYCL with KDOP<14>

### LINKED ISSUE #1234: SYCL QueryTree test fails for KDOP18 in CI
As in [here](https://cloud1.cees.ornl.gov/jenkins-ci/job/ArborX/job/PR-1232/5/testReport/junit/projectroot/test/Build___SYCL___ArborX_Test_QueryTree/):
```
Running 242 test cases...
/var/jenkins/workspace/ArborX_PR-1232/test/tstQueryTreeManufacturedSolution.cpp(108): error: in "ManufacturedSolution/structured_grid<TreeExecutionAndMemorySpaces<ArborX_Legacy_BVH_KDOP14_double_ Kokkos__Device<Kokkos__Experimental__SYCL_ Kokkos__Experimental__SYCLDeviceUSMSpace>>>": check query(ExecutionSpace{}, tree, queries) == (make_reference_solution(indices_ref, offset_ref)) has failed
  - mismatch at position 5: [( ) == ( 5 )] is false
  - mismatch at position 6: [( ) == ( 6 )] is false
  - mismatch at position 7: [( ) == ( 7 )] is false
<snip>
/var/jenkins/workspace/ArborX_PR-1232/test/tstQueryTreeManufacturedSolution.cpp(207): error: in "ManufacturedSolution/structured_grid<TreeExecutionAndMemorySpaces<ArborX_Legacy_BVH_KDOP14_double_ Kokkos__Device<Kokkos__Experimental__SYCL_ Kokkos__Experimental__SYCLDeviceUSMSpace>>>": check query(ExecutionSpace{}, tree, queries) == (make_reference_solution(indices_ref, offset_ref)) has failed
  - mismatch at position 8: [( ) == ( 7 8 9 18 19 20 128 129 130 139 140 141 )] is false
  - mismatch at position 9: [( ) == ( 8 9 10 19 20 21 129 130 131 140 141 142 )] is false
```
It started failing fairly recently, and worked before that.

Note, that we don't run KDOP18 and KDOP26 for NVCC either. There's something about these compilers that doesn't work.

### PR DESCRIPTION
**Pull request by aprokop**
Fix #1234

### CODE REVIEW

File: test/tstQueryTreeManufacturedSolution.cpp [hunk 1]
```diff
@@ -38,16 +38,22 @@ BOOST_AUTO_TEST_CASE_TEMPLATE(structured_grid, TreeTypeTraits,
...
   {
+#ifdef __NVCC__
+    // FIXME_NVCC we see inexplainable test failures with NVCC and KDOP<18> and
+    // KDOP<26> here.
     if constexpr (BoundingVolume::n_directions == 9 ||
                   BoundingVolume::n_directions == 13)
       return;
-  }
 #endif
+#ifdef __INTEL_LLVM_COMPILER
```
Comment (masterleinad) [inline test/tstQueryTreeManufacturedSolution.cpp:50]: Does it also fail when using `icpx` with host backends? Otherwise, I would rather check for `KOKKOS_ENABLE_SYCL`.

Comment (aprokop) [reply test/tstQueryTreeManufacturedSolution.cpp:50]: I'll need to check that.

Comment (aprokop) [reply test/tstQueryTreeManufacturedSolution.cpp:50]: It seems pretty intermittent in failures in our CI. Can't reproduce it on Aurora.

Comment (masterleinad) [reply test/tstQueryTreeManufacturedSolution.cpp:50]: Use `KOKKOS_IF_ON_HOST/DEVICE` which uses `__SYCL_DEVICE_ONLY__`.

Comment (masterleinad) [reply test/tstQueryTreeManufacturedSolution.cpp:51]: This isn't actually in device code, so you should use `if constexpr(std::is_same_v<ExecutionSpace, Kokkos::SYCL>)` instead.
