### PR TITLE
Fix scaling issues in the distributed driver for 1D and 2D

### LINKED ISSUE #218: Fix 1D and 2D domain scaling in the distributed benchmark
Currently, the domains are constructed as `[-a,a]^d`, where `d` is the partition dimension, and `a = std::cbrt(n_values)`. This way, the density of points stays constant in 3D. However, for 1D and 2D the density varies, and the same radius would produce different average results. The value of `a` should be set to `n_values` in 1D, and `std::sqrt(n_values)` in 2D.

### PR DESCRIPTION
**Pull request by aprokop**
Fix #218.

### CODE REVIEW

File: benchmarks/distributed_tree_driver/distributed_tree_driver.cpp [hunk 1]
```diff
@@ -402,6 +405,7 @@ int main_(std::vector<std::string> const &args, const MPI_Comm comm)
     // NOTE: minus "1+sqrt(3)/2 \approx 1.37" matches the size of the boxes
     // inserted into the tree (mid-point between half-edge and
     // half-diagonal)
+    // FIXME
```
Comment (aprokop) [inline benchmarks/distributed_tree_driver/distributed_tree_driver.cpp]: I need help fixing this. I don't remember now how this formula was computed, and we need to adapt it for both 2D and 1D.

Comment (aprokop) [reply benchmarks/distributed_tree_driver/distributed_tree_driver.cpp]: @dalg24 Do you remember the exact details of computing this? I have trouble reproducing the formula that is in the code.

**Comment by aprokop** [comment]
Rebased and fixed the radius calculations for 1D/2D. 

Running on a single rank (which should be representative) as
```shell
$ ./ArborX_DistributedTree.exe --values=1000000 --queries=20000 \
     --do-not-perform-knn-search --partition_dim=<dim>
```
now produces

| dim | min neighbors | max neighbors | avg neighbors |
| --- | --- | --- | --- | 
| 1 | 1 | 26 | 10 |
| 2 | 1 | 26 | 11 | 
| 3 | 1 | 28 | 12 |

which is pretty close to 10 that we want (this is only for the case of no overlap (shift = 0) and no shrinking).

The fact that the last column is not exactly 10 for 2D/3D is due to replacing complex integral by an approximation.

**Comment by aprokop** [comment]
Please review.

File: benchmarks/distributed_tree_driver/distributed_tree_driver.cpp [hunk 2]
```diff
@@ -387,8 +388,10 @@ int main_(std::vector<std::string> const &args, const MPI_Comm comm)
       for (int i = 0; i < n_queries; ++i)
         random_queries_host(i) = {
             {a * ((offset_x + random()) / 3 + max_offset / 3),
-             a * ((offset_y + random()) / 3 + max_offset / 3),
-             a * ((offset_z + random()) / 3 + max_offset / 3)}};
+             a * ((offset_y + random()) / 3 + max_offset / 3) *
+                 (partition_dim > 1),
```
Comment (masterleinad) [inline benchmarks/distributed_tree_driver/distributed_tree_driver.cpp:392]: Hmm... I would prefer not using implicit conversion between `bool` and built-in types and prefer ternary operators.

In the end, it doesn't matter if we always fill the second and third component, though, does it?

File: benchmarks/distributed_tree_driver/distributed_tree_driver.cpp [hunk 3]
```diff
@@ -293,17 +293,15 @@ int main_(std::vector<std::string> const &args, const MPI_Comm comm)
               << '\n';
   }
 
+  if (partition_dim < 1 || partition_dim > 3)
```
Comment (masterleinad) [inline benchmarks/distributed_tree_driver/distributed_tree_driver.cpp:296]: Any reason to move this?

File: benchmarks/distributed_tree_driver/distributed_tree_driver.cpp [hunk 4]
```diff
@@ -436,13 +439,29 @@ int main_(std::vector<std::string> const &args, const MPI_Comm comm)
...
+      break;
+    case 2:
+      // n_values*(M_PI*r^2)/(2a)^2 = n_neighbors
+      r = std::sqrt(static_cast<double>(n_neighbors) * 4. / M_PI) -
+          (1. + std::sqrt(2.)) / 2;
+      break;
+    case 3:
+      // n_values*(4/3*M_PI*r^3)/(2a)^3 = n_neighbors
+      r = std::cbrt(static_cast<double>(n_neighbors) * 6. / M_PI) -
+          (1. + std::cbrt(3.)) / 2;
```
Comment (masterleinad) [inline benchmarks/distributed_tree_driver/distributed_tree_driver.cpp:462]: Can you please comment a little more on the last term in all three cases?

File: benchmarks/distributed_tree_driver/distributed_tree_driver.cpp (hunk 2 above)
Comment (aprokop) [reply benchmarks/distributed_tree_driver/distributed_tree_driver.cpp:392]: It matters. We have to fill them with zeros. Otherwise, the distances (and thus density) change because we have an additional vertical distance to consider.

File: benchmarks/distributed_tree_driver/distributed_tree_driver.cpp (hunk 3 above)
Comment (aprokop) [reply benchmarks/distributed_tree_driver/distributed_tree_driver.cpp:296]: I think there was one, but can't recall it now and don't see why.

File: benchmarks/distributed_tree_driver/distributed_tree_driver.cpp (hunk 2 above)
Comment (masterleinad) [reply benchmarks/distributed_tree_driver/distributed_tree_driver.cpp:392]: Ah, right. I was thinking for a moment that we only copy the needed components for some reason.

File: benchmarks/distributed_tree_driver/distributed_tree_driver.cpp (hunk 4 above)
Comment (aprokop) [reply benchmarks/distributed_tree_driver/distributed_tree_driver.cpp:462]: I'm not sure what you want me to add to the comment above. This is the average of half-edge and half-diagonal.

Comment (masterleinad) [reply benchmarks/distributed_tree_driver/distributed_tree_driver.cpp:462]: I would prefer the formula to match what we implement.
So instead of just taking `r` from it, we make a little bit smaller and I am still a little bit confused about why this is necessary.

File: benchmarks/distributed_tree_driver/distributed_tree_driver.cpp [hunk 5]
```diff
@@ -436,13 +439,29 @@ int main_(std::vector<std::string> const &args, const MPI_Comm comm)
...
-    // inserted into the tree (mid-point between half-edge and
-    // half-diagonal)
-    double const r =
-        2. * std::cbrt(static_cast<double>(n_neighbors) * 3. / (4. * M_PI)) -
-        (1. + std::sqrt(3.)) / 2.;
+    // Radius is computed so that the number of results per query for a
+    // uniformly distributed points in a [-a,a]^d box is approximately
+    // n_neighbors. This requires adjusting as construction is based on
+    // [-1,1]^d boxes. Instead of an exact calculation using integrals,
+    // an approximation is made by averaging half-edge and half-diagonal).
```
Comment (masterleinad) [inline benchmarks/distributed_tree_driver/distributed_tree_driver.cpp:446]:
```suggestion
    // an approximation is made by averaging half-edge and half-diagonal.
```

File: benchmarks/distributed_tree_driver/distributed_tree_driver.cpp (hunk 4 above)
Comment (aprokop) [reply benchmarks/distributed_tree_driver/distributed_tree_driver.cpp:462]: The main thing why this is tricky is because in this driver we deal with boxes and not points. So, it is not sufficient to just consider the density of box centers, as even the boxes with centers that are farther apart may overlap. Thus, we need to decrease the radius.

The formula there is just for the density of of point cloud, i.e. first term. I found it helpful to understand that term. I can make an explicit comment about that.

Comment (masterleinad) [reply benchmarks/distributed_tree_driver/distributed_tree_driver.cpp:462]: Yes, please add something explaining that the primitives here are boxes and not points. Keeping that in mind it makes sense to have such a kind of correction. (On the other hand, I would not be opposed to just use points instead of boxes but that's for a later discussion I think).

Comment (aprokop) [reply benchmarks/distributed_tree_driver/distributed_tree_driver.cpp:462]: The comment above states: `This requires adjusting as construction is based on [-1,1]^d boxes.` I'm not sure what else I can add. I guess I can put another sentence there.

Comment (masterleinad) [reply benchmarks/distributed_tree_driver/distributed_tree_driver.cpp:462]: Something like
```
    // Radius is computed so that the number of results per query for a
    // uniformly distributed points in a [-a,a]^d box is approximately
    // n_neighbors. 
    // Note that the primitives considered here are not points but boxes.
    // The radius is decreased by averaging the length of a half-edge 
    // and the length of the half-diagonal to account for that approximately.
```
would work for me.
