### PR TITLE
Fix ambiguities arising from using initializer lists without specifying a type

### LINKED ISSUE #435: Use of initializer lists in tests without type leads to ambiguity (e.g., Box and Ray)
1. The function `ArborX::Details::intersects(const ArborX::Box &, const ArborX::Box &)` and function `ArborX::Details::intersects(const ArborX::Ray &, const ArborX::Box &)` are reported to have the same argument type: {{...},{...}}.
2. Should the `ArborX::Details::intersects(const ArborX::Ray &, const ArborX::Box &)` be put in the `ArborX_DetailsAlgorithms.hpp`? or should `ArborX_DetailsAlgorithms.hpp #include ArborX_Ray.hpp`?

### PR DESCRIPTION
**Pull request by wjge**
This is pr to make make ArborX::Ray working as a predicate for batched queries.
I ran into and then resolved an issue #435.

Fix #435

### CODE REVIEW

File: test/tstDetailsAlgorithms.cpp [hunk 1]
```diff
@@ -56,8 +56,8 @@ BOOST_AUTO_TEST_CASE(intersects)
   // uninitialized box does not even intersect with itself
   STATIC_ASSERT(!intersects(Box{}, Box{}));
   // box with zero extent does
-  STATIC_ASSERT(intersects({{{0.0, 0.0, 0.0}}, {{0.0, 0.0, 0.0}}},
-                           {{{0.0, 0.0, 0.0}}, {{0.0, 0.0, 0.0}}}));
+  STATIC_ASSERT(intersects(Box{{{0.0, 0.0, 0.0}}, {{0.0, 0.0, 0.0}}},
+                           Box{{{0.0, 0.0, 0.0}}, {{0.0, 0.0, 0.0}}}));
```
Comment (dalg24) [inline test/tstDetailsAlgorithms.cpp:60]: Make one commit for this with a message such as "Resolving ambiguity between intersects() Box and Ray overloads"

File: src/details/ArborX_DetailsAlgorithms.hpp [hunk 2]
```diff
@@ -208,6 +209,9 @@ Point returnCentroid(Box const &box)
 KOKKOS_INLINE_FUNCTION
 Point returnCentroid(Sphere const &sphere) { return sphere.centroid(); }
 
+KOKKOS_INLINE_FUNCTION
+Point returnCentroid(Ray const &ray) { return ray.origin(); }
```
Comment (dalg24) [inline src/details/ArborX_DetailsAlgorithms.hpp:213]: Make a commit with the changes to that file saying something like "Add Details::returnCentroid(Ray) implementation to enable interacts(Ray) predicate in batched queries"

**Review by dalg24 — COMMENTED** [review]
Please rewrite history (`git reset origin/master; git add -u -p` etc)
Looks good other than that

**Comment by aprokop** [comment]
I would ask to expand the scope of this PR to include all instances of free form initializer lists in that test file. For example, as soon as one implements `equals(Ray, Ray)`, things will not compile again.

**Comment by wjge** [comment]
> I would ask to expand the scope of this PR to include all instances of free form initializer lists in that test file. For example, as soon as one implements `equals(Ray, Ray)`, things will not compile again.

Could you suggest a grep keywords list to find all the instances?

**Comment by aprokop** [comment]
> Could you suggest a grep keywords list to find all the instances?

Something like this: `$ egrep ' {|\({' tstDetailsAlgorithms.cpp`

**Review by dalg24 — APPROVED** [review]
This is still trivial enough that I won't block but you should think about testing when you add functionality

**Comment by aprokop** [comment]
Whatever, I don't care enough to fix this all right now, and just kicked the ball down the road.
