### PR TITLE
Disable deprecated code

### LINKED ISSUE #28: Remove deprecated Kokkos
Make sure that we can build without deprecated features from Kokkos

### LINKED ISSUE #34: Compiling with Kokkos development branch doesn't work.
Error messages:
```
In file included from Arborx/src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp:17:0,
                 from Arborx/test/tstDetailsDistributedSearchTreeImpl.cpp:12:
Arborx/src/details/ArborX_DetailsUtils.hpp: In function ‘std::pair<typename ViewType::non_const_value_type, typename ViewType::non_const_value_type> ArborX::minMax(const ViewType&)’:
Arborx/src/details/ArborX_DetailsUtils.hpp:176:27: error: ‘MinMaxScalar’ is not a member of ‘Kokkos::Experimental’
     Kokkos::Experimental::MinMaxScalar<typename ViewType::non_const_value_type>
                           ^~~~~~~~~~~~
Arborx/src/details/ArborX_DetailsUtils.hpp:176:27: note: suggested alternative:
In file included from kokkos-install/include/Kokkos_Parallel.hpp:255:0,
                 from kokkos-install/include/Kokkos_Serial.hpp:55,
                 from kokkos-install/include/Kokkos_Core.hpp:53,
                 from Arborx/src/details/ArborX_DetailsDistributor.hpp:16,
                 from Arborx/src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp:14,
                 from Arborx/test/tstDetailsDistributedSearchTreeImpl.cpp:12:
kokkos-install/include/Kokkos_Parallel_Reduce.hpp:633:8: note:   ‘Kokkos::MinMaxScalar’
 struct MinMaxScalar {
        ^~~~~~~~~~~~
In file included from Arborx/src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp:17:0,
                 from Arborx/test/tstDetailsDistributedSearchTreeImpl.cpp:12:
Arborx/src/details/ArborX_DetailsUtils.hpp:176:79: error: expected ‘(’ before ‘>’ token
     Kokkos::Experimental::MinMaxScalar<typename ViewType::non_const_value_type>
                                                                               ^
Arborx/src/details/ArborX_DetailsUtils.hpp:177:9: error: ‘result’ was not declared in this scope
         result;
         ^~~~~~
Arborx/src/details/ArborX_DetailsUtils.hpp:178:27: error: ‘MinMax’ is not a member of ‘Kokkos::Experimental’
     Kokkos::Experimental::MinMax<typename ViewType::non_const_value_type>
                           ^~~~~~
Arborx/src/details/ArborX_DetailsUtils.hpp:178:27: note: suggested alternative:
In file included from kokkos-install/include/Kokkos_Core.hpp:50:0,
                 from Arborx/src/details/ArborX_DetailsDistributor.hpp:16,
                 from Arborx/src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp:14,
                 from Arborx/test/tstDetailsDistributedSearchTreeImpl.cpp:12:
kokkos-install/include/Kokkos_Core_fwd.hpp:317:61: note:   ‘Kokkos::MinMax’
 template<class ScalarType , class Space = HostSpace> struct MinMax;
                                                             ^~~~~~
In file included from Arborx/src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp:17:0,
                 from Arborx/test/tstDetailsDistributedSearchTreeImpl.cpp:12:
Arborx/src/details/ArborX_DetailsUtils.hpp:178:73: error: expected ‘(’ before ‘>’ token
     Kokkos::Experimental::MinMax<typename ViewType::non_const_value_type>
                                                                         ^
Arborx/src/details/ArborX_DetailsUtils.hpp:179:9: error: there are no arguments to ‘reducer’ that depend on a template parameter, so a declaration of ‘reducer’ must be available [-fpermissive]
         reducer( result );
         ^~~~~~~
Arborx/src/details/ArborX_DetailsUtils.hpp:179:9: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
Arborx/src/details/ArborX_DetailsUtils.hpp:182:55: error: ‘reducer’ was not declared in this scope
         Kokkos::Impl::min_max_functor<ViewType>( v ), reducer );
                                                       ^~~~~~~
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #28, fixes #34. Locally, all tests pass now. Needs some cleanup, though.

### CODE REVIEW

**Comment by masterleinad** [comment]
Rebased. I simply skipped all conflicting commits. The result passes the tests both with and without deprecations.

File: src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp [hunk 1]
```diff
@@ -137,11 +158,18 @@ create_layout_right_mirror_view(
...
       std::string(src.label()).append("_layout_right_mirror"), src.extent(0),
-      src.extent(1), src.extent(2), src.extent(3), src.extent(4), src.extent(5),
-      src.extent(6), src.extent(7));
+      pointer_depth > 1 ? src.extent(1) : KOKKOS_INVALID_INDEX,
+      pointer_depth > 2 ? src.extent(2) : KOKKOS_INVALID_INDEX,
+      pointer_depth > 3 ? src.extent(3) : KOKKOS_INVALID_INDEX,
+      pointer_depth > 4 ? src.extent(4) : KOKKOS_INVALID_INDEX,
+      pointer_depth > 5 ? src.extent(5) : KOKKOS_INVALID_INDEX,
+      pointer_depth > 6 ? src.extent(6) : KOKKOS_INVALID_INDEX,
+      pointer_depth > 7 ? src.extent(7) : KOKKOS_INVALID_INDEX);
```
Comment (dalg24) [inline src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp]: I suspect this is broken for compile-time dimensions

**Comment by masterleinad** [comment]
> Please drop [263eddd](https://github.com/arborx/ArborX/commit/263edddadd266dd9cc98fa92abb6c8de8a97d410) [6189eef](https://github.com/arborx/ArborX/commit/6189eef0b7b35ea43ced7e252f3860604d76f771) [69e1d45](https://github.com/arborx/ArborX/commit/69e1d4549604417a6b601c370cf5b2cfc878e4b8) [9eae04f](https://github.com/arborx/ArborX/commit/9eae04fe4dec4f40f42884a07b0fb829cb73c42b) [4d9b866](https://github.com/arborx/ArborX/commit/4d9b866cb77425a8bae2992fd3e03502e5e11ea8) [c14c657](https://github.com/arborx/ArborX/commit/c14c65738262ce341d1a5367a175b3001189809c) and fixup [d319429](https://github.com/arborx/ArborX/commit/d319429f275b39f0363423d07fa42a12bee15f83) into [de4b6a8](https://github.com/arborx/ArborX/commit/de4b6a8a2d087847ddd9424f85766d2903cdc079)

Fixed.

File: src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp [hunk 2]
```diff
@@ -123,6 +123,27 @@ struct DistributedSearchTreeImpl
                     typename View::non_const_type imports);
 };
 
+namespace internal
```
Comment (aprokop) [inline src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp]: Is this the right place for it? Or should it go to Kokkos utilities file?

Comment (aprokop) [reply src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp]: Also, do we want to test that somewhere?

Comment (dalg24) [reply src/details/ArborX_DetailsDistributedSearchTreeImpl.hpp]: @masterleinad So that you know, the convention in the Search package of DTK use to be `namespace Details { ... }`.  I am not asking you to change, it is just a FYI.  `internal` is standard enough and it will be easy to grep for it.

@aprokop It is the right place for now as it is only used here.

About testing, I guess we could add a test with a view that has compile-time dimension in the  `create_layout_right_mirror_view` test case and it would be good enough.
