### PR TITLE
Buffer optimization fix for empty results

### LINKED ISSUE #205: Allow buffer optimization with size zero
Weird use case a callback is used to get the results out and `insert()` never gets called.
The problem is this triggers the second pass which is totally unnecessary.

### PR DESCRIPTION
**Pull request by aprokop**
Fix #205.

### CODE REVIEW

**Comment by aprokop** [comment]
This fix properly avoid unnecessary `max` call in this situation, compared to the approach proposed in the [issue comment](https://github.com/arborx/ArborX/issues/205#issuecomment-573150906).

File: src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp [hunk 1]
```diff
@@ -381,6 +381,9 @@ BoundingVolumeHierarchyImpl<DeviceType>::queryDispatch(
   using Access = Traits::Access<Predicates, Traits::PredicatesTag>;
   auto const n_queries = Access::size(predicates);
 
+  bool const throw_if_buffer_optimization_fails = (buffer_size < 0);
```
Comment (masterleinad) [inline src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp]: It should be documented not just in an internal file what a negative value should imply.

File: src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp [hunk 2]
```diff
@@ -490,7 +482,10 @@ BoundingVolumeHierarchyImpl<DeviceType>::queryDispatch(
 
   Kokkos::Profiling::popRegion();
 
-  if (max_results_per_query > buffer_size)
+  // The check for the number of results is for an unusual situation that may
+  // happen when either no results were found, or nothing was inserted inside a
+  // callback for found results.
+  if (n_results && (max_results_per_query > buffer_size))
```
Comment (masterleinad) [inline src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp]:
```suggestion
  if (n_results > 0 && (max_results_per_query > buffer_size))
```

File: src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp [hunk 3]
```diff
@@ -523,8 +518,8 @@ BoundingVolumeHierarchyImpl<DeviceType>::queryDispatch(
 
     Kokkos::Profiling::popRegion();
   }
-  // do not copy if by some miracle each query exactly yielded as many results
-  // as the buffer size
+  // Do not copy if each query exactly yielded as many results
+  // as the buffer size, or if both are zero.
```
Comment (masterleinad) [inline src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp]: I would just omit it since you don't consider it in the if switch anyway. Alternatively, you could just do
```
if (n_results > 0)
{
  if (max_results_per_query > buffer_size)
  {
    ...
  }
  else if (n_results != static_cast<int>(n_queries) * buffer_size)
  {
    ...
  }
}
```
for clarity.

File: src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp (hunk 1 above)
Comment (aprokop) [reply src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp]: As we expect API to change, we don't document this or expose it to users yet.

File: src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp (hunk 2 above)
Comment (aprokop) [reply src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp]: Meh, I don't think this is necessary.

File: src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp (hunk 3 above)
Comment (aprokop) [reply src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp]: I thought about doing that, but thought it may look good. Don't really care.

File: src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp (hunk 2 above)
Comment (masterleinad) [reply src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp]: This is one of the things that make me think for a second what is meant. IMHO, it's totally worth to be explicit and not to rely on the implicit conversion to a bool value.

File: src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp (hunk 1 above)
Comment (masterleinad) [reply src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp]: Hyrum's law still applies. :wink:

Comment (aprokop) [reply src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp]: OK, I invoke "out of scope for this PR".

**Comment by aprokop** [comment]
@masterleinad OK, I simplified the code by simply exiting early.

File: src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp [hunk 4]
```diff
@@ -490,6 +482,15 @@ BoundingVolumeHierarchyImpl<DeviceType>::queryDispatch(
 
   Kokkos::Profiling::popRegion();
 
+  // Exit early if either no results were found for any of the queries, or
+  // nothing was inserted inside a callback for found results. This check
+  // allows to avoid the second pass when buffer_size is 0.
```
Comment (masterleinad) [inline src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp]: Is this really correct? Don't we still do the second pass if `buffer_size==0`?
