### PR TITLE
Fix bug with command line parsing in bvh example

### LINKED ISSUE #52: Passing options to ArborX_BoundingVolumeHierarchy.exe broken
Running
```
 $ ./ArborX_BoundingVolumeHierarchy.exe --values=10000000
```
gives
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >'
  what():  unrecognised option '--values=10000000'
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by dalg24**
Closes #52 

Couldn't figure out how to make the parser consume arguments with Boost.Program_options.  This is not pretty but it does the trick.

### CODE REVIEW

File: examples/bvh_driver/bvh_driver.cpp [hunk 1]
```diff
@@ -245,6 +245,33 @@ class KokkosScopeGuard
...
       ->Unit(benchmark::kMicrosecond);
 
+class CmdLineArgs
+{
+  int argc_;
+  std::vector<char *> argv_;
+
+public:
+  CmdLineArgs(std::vector<std::string> const &args, char *exe)
+          : argc_(args.size() + 1), argv_{{exe}}
```
Comment (dalg24) [inline examples/bvh_driver/bvh_driver.cpp]: NOTE: this is a bit sketchy because it assumes the executable name does not get out of scope...

File: examples/bvh_driver/bvh_driver.cpp [hunk 2]
```diff
@@ -245,6 +245,33 @@ class KokkosScopeGuard
...
+    {
+      argv_.push_back(new char[s.size() + 1]);
+      std::strcpy(argv_.back(), s.c_str());
+    }
+  }
+  ~CmdLineArgs()
+  {
+    for (auto &p : argv_)
+    {
+      delete[] p;
```
Comment (dalg24) [inline examples/bvh_driver/bvh_driver.cpp]: Dammit I attempted deleting the 1st element...

Comment (dalg24) [reply examples/bvh_driver/bvh_driver.cpp]: Fixed

File: examples/bvh_driver/CMakeLists.txt [hunk 3]
```diff
@@ -23,4 +23,4 @@ find_package (Threads REQUIRED)
 add_executable(ArborX_BoundingVolumeHierarchy.exe bvh_driver.cpp)
 target_link_libraries(ArborX_BoundingVolumeHierarchy.exe ${ArborX_TARGET} benchmark::benchmark Boost::program_options Threads::Threads)
 target_include_directories(ArborX_BoundingVolumeHierarchy.exe PRIVATE ${POINT_CLOUDS_INCLUDE_DIR} ${UNIT_TESTS_INCLUDE_DIR})
-add_test(NAME ArborX_BoundingVolumeHierarchy_Example COMMAND ./ArborX_BoundingVolumeHierarchy.exe)
+add_test(NAME ArborX_BoundingVolumeHierarchy_Example COMMAND ./ArborX_BoundingVolumeHierarchy.exe --buffer=0 --benchmark_color=true)
```
Comment (Rombur) [inline examples/bvh_driver/CMakeLists.txt]: Does the coloring works with Jenkins/ctest or do we get something unreadable where we get a bunch of color tags in the log file?

File: examples/bvh_driver/bvh_driver.cpp [hunk 4]
```diff
@@ -245,6 +245,38 @@ class KokkosScopeGuard
       ->UseManualTime()                                                        \
       ->Unit(benchmark::kMicrosecond);
 
+// NOTE Motivation for this class that stores the argument count and values is
+// I could not figure out how to make the parser consume arguments with
+// Boost.Program_options
+class CmdLineArgs
+{
+  int argc_;
+  std::vector<char *> argv_;
```
Comment (Rombur) [inline examples/bvh_driver/bvh_driver.cpp]: Error prone way to set something private. Also, I thought that private variables started with an `_`

Comment (Rombur) [reply examples/bvh_driver/bvh_driver.cpp]: Why are using raw pointers?

File: examples/bvh_driver/bvh_driver.cpp [hunk 5]
```diff
@@ -245,6 +245,38 @@ class KokkosScopeGuard
...
+      , argv_{{new char[std::strlen(exe)]}}
+  {
+    std::strcpy(argv_[0], exe);
+    argv_.reserve(argc_);
+    for (auto const &s : args)
+    {
+      argv_.push_back(new char[s.size() + 1]);
+      std::strcpy(argv_.back(), s.c_str());
+    }
+  }
```
Comment (Rombur) [inline examples/bvh_driver/bvh_driver.cpp]: Add a blank line

File: examples/bvh_driver/bvh_driver.cpp [hunk 6]
```diff
@@ -269,11 +301,14 @@ int main(int argc, char *argv[])
...
-                                 .run();
-  bpo::store(opts, vm);
+  bpo::parsed_options parsed = bpo::command_line_parser(argc, argv)
+                                   .options(desc)
+                                   .allow_unregistered()
+                                   .run();
+  bpo::store(parsed, vm);
+  CmdLineArgs pass_further{
+      bpo::collect_unrecognized(parsed.options, bpo::include_positional),
+      argv[0]};
```
Comment (Rombur) [inline examples/bvh_driver/bvh_driver.cpp]: Wait so we are using boost::PO for some arguments and the new code for others? What's so special about the new arguments?

Comment (dalg24) [reply examples/bvh_driver/bvh_driver.cpp]: The parsings goes like this:
1. Kokkos parse its own args and consume them like it should
2. We then parse the remaining arguments but cannot throw when args are not recognized because they might be some that go to Google benchmark
3. Benchmark consume their own args
4. We ensure all arguments have been consumed using BPO

File: examples/bvh_driver/bvh_driver.cpp (hunk 4 above)
Comment (dalg24) [reply examples/bvh_driver/bvh_driver.cpp]: Because you can't get a `char **` with a vector of strings

File: examples/bvh_driver/CMakeLists.txt (hunk 3 above)
Comment (dalg24) [reply examples/bvh_driver/CMakeLists.txt]: I haven't checked.  I picked randomly one of the options to make sure it works.

Comment (dalg24) [reply examples/bvh_driver/CMakeLists.txt]: Do you want me to change to `auto`?

File: examples/bvh_driver/bvh_driver.cpp (hunk 6 above)
Comment (dalg24) [reply examples/bvh_driver/bvh_driver.cpp]: You might ask why aren't we doing 1, 3, (2+4)

It is because of Google benchmark calling `std::exit(0)` when `--help` is passed :(

For reference: https://github.com/google/benchmark/blob/33d440465041fe83b831f537b9646756655806f0/src/benchmark.cc#L426

File: examples/bvh_driver/CMakeLists.txt (hunk 3 above)
Comment (Rombur) [reply examples/bvh_driver/CMakeLists.txt]: I don't care what we use as long as the log is readable

Comment (dalg24) [reply examples/bvh_driver/CMakeLists.txt]: > I don't care what we use as long as the log is readable

Yeah...  About that.  Have you looked at the logs on Jenkins?  This is another of these need to fix

**Comment by dalg24** [comment]
Fixed the style

File: examples/bvh_driver/CMakeLists.txt (hunk 3 above)
Comment (masterleinad) [reply examples/bvh_driver/CMakeLists.txt]: The log file is deleted anyway because it is too large...
