### PR TITLE
Change signature of the nearest callback

### LINKED ISSUE #355: Consider changing nearest callback signature to that of spatial (i.e., remove distance argument)
kNN is typically used for classification, or regression. In both cases, one is interested in deducing the property of an object from the properties of neighbors. It is common to compute a weighted average, where the weights are inverse distances.

Pros:
- It would simplify code internally
- The distance may be confusing, as it is a distance to the leaf bounding box, but not necessarily to the user object

Cons:
- It could theoretically make some algorithms do more on a user's side through extra distance computation
- **Need nearest callbacks for the distributed tree as otherwise getting distance would require reaching across the network**

I'm leaning towards doing this change, as a) it seems unlikely that extra distance computations would have significant affect on the overall performance of the algorithm, and b) code maintenance of the feature is significant while having few if any users for it.

P.S. To my knowledge, we don't have anyone using nearest callbacks at the moment.

### PR DESCRIPTION
**Pull request by aprokop**
Fix #355

### CODE REVIEW

**Comment by aprokop** [comment]
Decided to quickly redo this as this will heavily conflict with #425.

File: src/details/ArborX_DetailsTreeTraversal.hpp [hunk 1]
```diff
@@ -25,6 +25,42 @@ namespace ArborX
...
+  Kokkos::View<unsigned int *, typename BVH::memory_space> rev_permute(
+      Kokkos::ViewAllocateWithoutInitializing(
+          "ArborX::DistributedTree::query::nearest::reverse_permutation"),
+      n);
+  Kokkos::parallel_for(
+      "ArborX::DistributedTree::query::nearest::compute_reverse_permutation",
+      Kokkos::RangePolicy<ExecutionSpace>(exec_space, 0, n),
+      KOKKOS_LAMBDA(int const i) {
+        rev_permute(leaf_nodes(i).getLeafPermutationIndex()) = i;
+      });
```
Comment (aprokop) [inline src/details/ArborX_DetailsTreeTraversal.hpp:58]: This was actually a nice idea. Mostly, because it avoids all the semantics of when and how to store user primitives, or extra arrays. It completely bypasses this question, because it is possible to figure out reverse permutation from the leave nodes, which are accessible during `query`.

File: src/details/ArborX_DetailsTreeTraversal.hpp [hunk 2]
```diff
@@ -25,6 +25,42 @@ namespace ArborX
...
+{
+  int const leaf_nodes_shift = bvh.size() - 1;
+  return bvh.getBoundingVolume(
+      bvh.getNodePtr(rev_permute(leaf_index) + leaf_nodes_shift));
+}
+
+template <typename ExecutionSpace, typename BVH>
+Kokkos::View<unsigned int *, typename BVH::memory_space>
+getReversePermutation(ExecutionSpace const &exec_space, BVH const &bvh)
+{
```
Comment (aprokop) [inline src/details/ArborX_DetailsTreeTraversal.hpp:45]: Not a fan of where this functions leave. They are only used by the distributed tree. But, in order to make functions friends to `BVH`, their declaration (or definition) must be available prior to that, which is not possible with distributed.

**Review by aprokop — COMMENTED** [review]
Overall, the patch is pretty straightforward. The only thing I'm not happy with is where the extra function leave. Any ideas welcome.

File: src/details/ArborX_DetailsDistributedTreeImpl.hpp [hunk 3]
```diff
@@ -417,6 +449,9 @@ DistributedTreeImpl<DeviceType>::queryDispatchImpl(
   // recompute everything instead of just searching for potential better
   // neighbors and updating the list.
 
+  CallbackWithDistance<BVH<typename DeviceType::memory_space>>
```
Comment (aprokop) [inline src/details/ArborX_DetailsDistributedTreeImpl.hpp:452]: Not sure if I should try to fix it to something like `std::decay_t<decltype(bottom_tree)>`. It is still completely tied to `BVH` and won't work with anything else.

**Review by masterleinad — COMMENTED** [review]
This looks reasonable but can you please comment on the disabled tests?

File: src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp [hunk 4]
```diff
@@ -89,103 +89,47 @@ struct Iota
...
-          typename Indices, typename Offset>
-inline std::enable_if_t<Kokkos::is_view<Indices>{} && Kokkos::is_view<Offset>{}>
-queryDispatch(SpatialPredicateTag, BVH const &bvh, ExecutionSpace const &space,
-              Predicates const &predicates, Indices &indices, Offset &offset,
-              Experimental::TraversalPolicy const &policy =
-                  Experimental::TraversalPolicy())
-{
-  queryDispatch(SpatialPredicateTag{}, bvh, space, predicates,
-                CallbackDefaultSpatialPredicate{}, indices, offset, policy);
+  exclusivePrefixSum(space, offset);
```
[the remark this answers is not in the document]
Comment (aprokop) [reply src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp:106]: You are right.

File: test/tstCallbacks.cpp [hunk 5]
```diff
@@ -124,49 +103,28 @@ int main()
...
-  //                     NearestPredicates{}, v);
+  // Uncomment to see error messages
 
-  // check_valid_callback(ArborX::Details::CallbackDefaultNearestPredicate{},
+  // check_valid_callback(PredicateCallbackDoesNotTakeCorrectArgument{},
   //                     SpatialPredicates{}, v);
 
-  check_valid_callback(CustomCallbackNearestPredicate{}, NearestPredicates{});
-
-  check_valid_callback(CustomCallbackSpatialPredicate{}, SpatialPredicates{});
```
[the remark this answers is not in the document]
Comment (aprokop) [reply test/tstCallbacks.cpp:144]: These were not removed, simply moved them up.

File: test/tstCallbacks.cpp [hunk 6]
```diff
@@ -124,49 +103,28 @@ int main()
...
-  // check_valid_callback(CustomCallbackSpatialPredicate{},
-  // NearestPredicates{});
-
 #ifndef __NVCC__
-  check_valid_callback([](auto const & /*predicate*/, int /*primitive*/) {},
-                       SpatialPredicates{});
-
-  check_valid_callback(
-      [](auto const & /*predicate*/, int /*primitive*/, float /*distance*/) {},
-      NearestPredicates{});
```
[the remark this answers is not in the document]
Comment (aprokop) [reply test/tstCallbacks.cpp:166]: No, these were not removed, but also moved up in the first `#ifndef __NVCC__` clause.

**Comment by aprokop** [comment]
@masterleinad Thanks for the review. I'll fix `exclusivePrefixSum` once @dalg24 reviews, so that I can push them together.

File: src/ArborX_LinearBVH.hpp [hunk 7]
```diff
@@ -106,6 +120,12 @@ class BoundingVolumeHierarchy
     return Kokkos::subview(_internal_and_leaf_nodes,
                            std::make_pair(size() - 1, 2 * size() - 1));
   }
+  Kokkos::View<node_type *, MemorySpace> getLeafNodes() const
```
Comment (dalg24) [inline src/ArborX_LinearBVH.hpp:123]: Any reason not to const the value type?   `Kokkos::View<node_type const *, ...>`

File: test/Search_UnitTestHelpers.hpp [hunk 8]
```diff
@@ -107,23 +107,6 @@ auto query(ExecutionSpace const &exec_space, Tree const &tree,
...
-  Kokkos::View<Kokkos::pair<int, float> *, memory_space> values(
-      "Testing::values", 0);
-  Kokkos::View<int *, memory_space> offsets("Testing::offsets", 0);
-  tree.query(exec_space, queries,
-             ArborX::Details::CallbackDefaultNearestPredicateWithDistance{},
-             values, offsets);
-  return make_compressed_storage(
-      Kokkos::create_mirror_view_and_copy(Kokkos::HostSpace{}, offsets),
-      Kokkos::create_mirror_view_and_copy(Kokkos::HostSpace{}, values));
-}
```
[the remark this answers is not in the document]
Comment (aprokop) [reply test/Search_UnitTestHelpers.hpp:125]: DistributedTree has a (deprecated) query dispatch that returns distances. If we want to maintain backwards compatibility, it has to be kept and tested.

File: src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp [hunk 9]
```diff
@@ -196,104 +140,70 @@ queryDispatch(NearestPredicateTag, BVH const &bvh, ExecutionSpace const &space,
 
   check_valid_callback(callback, predicates, out);
 
-  Kokkos::Profiling::pushRegion("ArborX::BVH::query::nearest");
+  Kokkos::Profiling::pushRegion("ArborX::BVH::query");
```
[the remark this answers is not in the document]
Comment (aprokop) [reply src/details/ArborX_DetailsBoundingVolumeHierarchyImpl.hpp:143]: No, we don't. I'll put them back.

**Comment by aprokop** [comment]
@masterleinad @dalg24 Should have addressed all your comments.

**Comment by aprokop** [comment]
PGI seems to fail sporadically, same error as in #430:
```
The library attempted to open the following supporting CUDA libraries,
but each of them failed.  CUDA-aware support is disabled.
libcuda.so.1: cannot open shared object file: No such file or directory
libcuda.dylib: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.so.1: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.dylib: cannot open shared object file: No such file or directory
If you are not interested in CUDA-aware support, then run with
--mca mpi_cuda_support 0 to suppress this message.  If you are interested
in CUDA-aware support, then try setting LD_LIBRARY_PATH to the location
of libcuda.so.1 to get passed this issue.
```
PGI was running on `cpu_node_4`. We don't enable CUDA in PGI testing, so it's unclear to me why it was searching for it. Interestingly, when tests passed before, PGI was also running on `cpu_node_4`. So, despite running on the same node, it sometimes fail. 🤷.

**Review by masterleinad — APPROVED** [review]
Fine with me.

**Comment by aprokop** [comment]
retest this please

File: src/details/ArborX_DetailsTreeTraversal.hpp [hunk 10]
```diff
@@ -25,6 +25,45 @@ namespace ArborX
...
+    Kokkos::parallel_for(
+        "ArborX::DistributedTree::query::nearest::compute_reverse_permutation",
+        Kokkos::RangePolicy<ExecutionSpace>(exec_space, 0, n),
+        KOKKOS_LAMBDA(int const i) {
+          rev_permute(leaf_nodes(i).getLeafPermutationIndex()) = i;
+        });
+  }
+
+  return rev_permute;
+}
```
Comment (dalg24) [inline src/details/ArborX_DetailsTreeTraversal.hpp:65]: I don't really like that you put these here but I suppose we can move later.

File: .clang-tidy [hunk 11]
```diff
@@ -1,5 +1,5 @@
 ---
-Checks:          'clang-diagnostic-*,clang-analyzer-*,-*,performance-*,-performance-inefficient-string-concatenation,mpi-*,modernize-*,-modernize-pass-by-value,-modernize-use-trailing-return-type,-modernize-avoid-c-arrays,readability-*,-readability-braces-around-statements,-readability-named-parameter,-readability-magic-numbers,-readability-uppercase-literal-suffix'
+Checks:          'clang-diagnostic-*,clang-analyzer-*,-*,performance-*,-performance-inefficient-string-concatenation,mpi-*,modernize-*,-modernize-pass-by-value,-modernize-use-trailing-return-type,-modernize-avoid-c-arrays,readability-*,-readability-braces-around-statements,-readability-named-parameter,-readability-magic-numbers,-readability-uppercase-literal-suffix,-readability-redundant-declaration'
```
Comment (dalg24) [inline .clang-tidy:2]: Are you referring to friend **function** declaration?

**Review by dalg24 — COMMENTED** [review]
OK with me after we clarify the Clang-Tidy check removal

File: src/details/ArborX_DetailsTreeTraversal.hpp (hunk 10 above)
Comment (aprokop) [reply src/details/ArborX_DetailsTreeTraversal.hpp:65]: Where would you put these?

File: .clang-tidy (hunk 11 above)
Comment (aprokop) [reply .clang-tidy:2]: In the commit message that introduced this change I mentioned:
```
A friend declaration inside a class counts as a declaration, so if we
also declare that friend outside the class, that will trigger a
redundant declaration warning from this check.
```
I'm not sure this answers your question, as honestly I don't understand what you are asking.

**Comment by aprokop** [comment]
I changed to using friend class declaration instead of two friend functions. I also reverted clang-tidy check. @dalg24 This should address all your comments.

On a side note, I wasted a lot of time trying to figure out why it did not work. It was an easy thing of forgetting to include `ArborX_Config.hpp` which had `ARBORX_ENABLE_MPI` macro. But the compiler error was useless as it was simply saying that something is private but not why.

This is not the first time I got burned by forgetting to include that header. Does anyone know if we can have a check that if a file uses any macro with a name from the config file, the config file has to be included?

**Comment by masterleinad** [comment]
> This is not the first time I got burned by forgetting to include that header. Does anyone know if we can have a check that if a file uses any macro with a name from the config file, the config file has to be included?

Our `headers_self_contained` test should do exactly that...

**Comment by aprokop** [comment]
> Our `headers_self_contained` test should do exactly that...

No. It only tests whether the standalone header can be compiled. But the issue here is that it can be compiled even when you use macros from the config header without including it. The protected code is simply compiled away.

**Comment by masterleinad** [comment]
If it includes a macro, it should be in `ArborX_HEADERS_MUST_INCLUDE_CONFIG_HPP` and for those we check that `ArborX_Config.hpp` is (transitively) included AFAICT.

**Comment by aprokop** [comment]
> If it includes a macro, it should be in `ArborX_HEADERS_MUST_INCLUDE_CONFIG_HPP` and for those we check that `ArborX_Config.hpp` is (transitively) included AFAICT.

I guess I got burned accidentally here, as this `ArborX_LinearBVH.hpp` was not part of `ArborX_HEADERS_MUST_ENABLE_MPI`.

**Comment by aprokop** [comment]
again random hip failure

retest this please

**Comment by aprokop** [comment]
retest this please

**Review by dalg24 — CHANGES_REQUESTED** [review]
Not requesting change but making sure it does not get merged "too early"

**Comment by aprokop** [comment]
Another randomly failing test: distributed tree on PGI. Can be merged.

**Comment by aprokop** [comment]
retest this please

**Comment by aprokop** [comment]
@dalg24 You dismissed your review, but did not approve. Should I understand it as you are going to do a final look?

File: src/details/ArborX_DetailsDistributedTreeImpl.hpp (hunk 3 above)
Comment (dalg24) [reply src/details/ArborX_DetailsDistributedTreeImpl.hpp:494]: Just add a comment before you merge

**Review by dalg24 — APPROVED** [review]

**Comment by aprokop** [comment]
@dalg24 thanks!

**Comment by aprokop** [comment]
I completely forgot to performance test this PR. And results look very fishy (I compared 9c4ae2d with 6224c97):
- smallest construction in Serial is up 12%
- OpenMP is completely screwed up
- smallest radius searching in Cuda are 10-20% faster

## Serial
```
BM_construction<ArborX::BVH<Serial>>/10000/0/manual_time_median                                     +0.1212         +0.1235          1836          2059          1905          2140
BM_construction<ArborX::BVH<Serial>>/100000/0/manual_time_median                                    +0.0197         +0.0199         16209         16528         16277         16601
BM_construction<ArborX::BVH<Serial>>/1000000/0/manual_time_median                                   +0.0099         +0.0101        174376        176096        174836        176610
BM_construction<ArborX::BVH<Serial>>/10000/1/manual_time_median                                     +0.1113         +0.1111          1816          2018          1883          2093
BM_construction<ArborX::BVH<Serial>>/100000/1/manual_time_median                                    +0.0130         +0.0134         16007         16215         16073         16288
BM_construction<ArborX::BVH<Serial>>/1000000/1/manual_time_median                                   +0.0090         +0.0090        171973        173518        172479        174037
BM_knn_search<ArborX::BVH<Serial>>/10000/10000/10/1/0/2/manual_time_median                          -0.0018         -0.0018         53269         53173         53265         53167
BM_knn_search<ArborX::BVH<Serial>>/100000/100000/10/1/0/2/manual_time_median                        +0.0006         +0.0006        559446        559762        559381        559705
BM_knn_search<ArborX::BVH<Serial>>/1000000/1000000/10/1/0/2/manual_time_median                      +0.0003         +0.0002       5955020       5956651       5954490       5955968
BM_knn_search<ArborX::BVH<Serial>>/10000/10000/10/1/1/3/manual_time_median                          +0.0009         +0.0007         52921         52970         52931         52966
BM_knn_search<ArborX::BVH<Serial>>/100000/100000/10/1/1/3/manual_time_median                        +0.0041         +0.0041        714774        717737        714703        717653
BM_knn_search<ArborX::BVH<Serial>>/1000000/1000000/10/1/1/3/manual_time_median                      +0.0030         +0.0030       9925856       9956042       9924945       9955031
BM_knn_search<ArborX::BVH<Serial>>/10000/10000/10/0/0/2/manual_time_median                          +0.0029         +0.0029         54750         54911         54747         54907
BM_knn_search<ArborX::BVH<Serial>>/100000/100000/10/0/0/2/manual_time_median                        +0.0047         +0.0047        587441        590200        587363        590130
BM_knn_search<ArborX::BVH<Serial>>/1000000/1000000/10/0/0/2/manual_time_median                      +0.0032         +0.0031       6571571       6592393       6569598       6590117
BM_knn_search<ArborX::BVH<Serial>>/10000/10000/10/0/1/3/manual_time_median                          +0.0040         +0.0043         59255         59494         59250         59507
BM_knn_search<ArborX::BVH<Serial>>/100000/100000/10/0/1/3/manual_time_median                        +0.0028         +0.0028        830907        833213        830800        833106
BM_knn_search<ArborX::BVH<Serial>>/1000000/1000000/10/0/1/3/manual_time_median                      +0.0019         +0.0019      11892630      11915662      11889060      11911844
BM_radius_search<ArborX::BVH<Serial>>/10000/10000/10/1/0/0/2/manual_time_median                     -0.0023         -0.0022         63867         63722         63856         63716
BM_radius_search<ArborX::BVH<Serial>>/100000/100000/10/1/0/0/2/manual_time_median                   -0.0024         -0.0024        667401        665791        667315        665712
BM_radius_search<ArborX::BVH<Serial>>/1000000/1000000/10/1/0/0/2/manual_time_median                 -0.0046         -0.0046       7068884       7036547       7068278       7035965
BM_radius_search<ArborX::BVH<Serial>>/10000/10000/10/1/0/1/3/manual_time_median                     -0.0098         -0.0098         16352         16192         16352         16192
BM_radius_search<ArborX::BVH<Serial>>/100000/100000/10/1/0/1/3/manual_time_median                   -0.0001         -0.0001        119377        119361        119364        119349
BM_radius_search<ArborX::BVH<Serial>>/1000000/1000000/10/1/0/1/3/manual_time_median                 -0.0025         -0.0024       1153948       1151064       1153564       1150833
BM_radius_search<ArborX::BVH<Serial>>/10000/10000/10/1/10/0/2/manual_time_median                    -0.0009         -0.0009         64790         64731         64785         64726
BM_radius_search<ArborX::BVH<Serial>>/100000/100000/10/1/10/0/2/manual_time_median                  +0.0002         +0.0002        676075        676198        675985        676121
BM_radius_search<ArborX::BVH<Serial>>/1000000/1000000/10/1/10/0/2/manual_time_median                +0.0000         +0.0000       7211538       7211730       7210964       7211274
BM_radius_search<ArborX::BVH<Serial>>/10000/10000/10/1/10/1/3/manual_time_median                    -0.0043         -0.0044         16680         16608         16681         16608
BM_radius_search<ArborX::BVH<Serial>>/100000/100000/10/1/10/1/3/manual_time_median                  +0.0005         +0.0005        121829        121885        121817        121873
BM_radius_search<ArborX::BVH<Serial>>/1000000/1000000/10/1/10/1/3/manual_time_median                -0.0034         -0.0033       1179443       1175492       1179201       1175278
BM_radius_search<ArborX::BVH<Serial>>/10000/10000/10/0/0/0/2/manual_time_median                     -0.0046         -0.0045         68355         68042         68349         68040
BM_radius_search<ArborX::BVH<Serial>>/100000/100000/10/0/0/0/2/manual_time_median                   -0.0041         -0.0041        740039        737005        739961        736899
BM_radius_search<ArborX::BVH<Serial>>/1000000/1000000/10/0/0/0/2/manual_time_median                 -0.0041         -0.0042       8449260       8414275       8446243       8411116
BM_radius_search<ArborX::BVH<Serial>>/10000/10000/10/0/0/1/3/manual_time_median                     -0.0010         -0.0010         20575         20555         20575         20555
BM_radius_search<ArborX::BVH<Serial>>/100000/100000/10/0/0/1/3/manual_time_median                   -0.0045         -0.0045        143086        142436        143071        142425
BM_radius_search<ArborX::BVH<Serial>>/1000000/1000000/10/0/0/1/3/manual_time_median                 -0.0077         -0.0078       1167207       1158162       1167049       1157979
BM_radius_search<ArborX::BVH<Serial>>/10000/10000/10/0/10/0/2/manual_time_median                    +0.0073         +0.0076         69214         69717         69186         69711
BM_radius_search<ArborX::BVH<Serial>>/100000/100000/10/0/10/0/2/manual_time_median                  +0.0138         +0.0138        743682        753933        743597        753830
BM_radius_search<ArborX::BVH<Serial>>/1000000/1000000/10/0/10/0/2/manual_time_median                +0.0118         +0.0118       8507355       8607678       8504369       8604592
BM_radius_search<ArborX::BVH<Serial>>/10000/10000/10/0/10/1/3/manual_time_median                    +0.0087         +0.0087         20945         21126         20944         21126
BM_radius_search<ArborX::BVH<Serial>>/100000/100000/10/0/10/1/3/manual_time_median                  +0.0099         +0.0098        144733        146163        144725        146149
BM_radius_search<ArborX::BVH<Serial>>/1000000/1000000/10/0/10/1/3/manual_time_median                +0.0010         +0.0009       1185640       1186769       1185434       1186557
```

## OpenMP
```
BM_construction<ArborX::BVH<OpenMP>>/10000/0/manual_time_median                                     +1.1524         +1.2087           338           728           348           769
BM_construction<ArborX::BVH<OpenMP>>/100000/0/manual_time_median                                    +0.2251         +0.2386          1556          1906          1571          1946
BM_construction<ArborX::BVH<OpenMP>>/1000000/0/manual_time_median                                   +0.0187         +0.0196         14745         15021         15309         15610
BM_construction<ArborX::BVH<OpenMP>>/10000/1/manual_time_median                                     +1.0849         +1.1423           351           732           361           774
BM_construction<ArborX::BVH<OpenMP>>/100000/1/manual_time_median                                    +0.1825         +0.1952          1742          2060          1757          2100
BM_construction<ArborX::BVH<OpenMP>>/1000000/1/manual_time_median                                   +0.0167         +0.0175         17438         17730         18004         18319
BM_knn_search<ArborX::BVH<OpenMP>>/10000/10000/10/1/0/2/manual_time_median                          +0.3040         +0.3038          1873          2442          1875          2444
BM_knn_search<ArborX::BVH<OpenMP>>/100000/100000/10/1/0/2/manual_time_median                        +0.0227         +0.0247         15631         15985         15249         15627
BM_knn_search<ArborX::BVH<OpenMP>>/1000000/1000000/10/1/0/2/manual_time_median                      -0.0045         -0.0099        159388        158674        158062        156496
BM_knn_search<ArborX::BVH<OpenMP>>/10000/10000/10/1/1/3/manual_time_median                          +0.2487         +0.2486          2262          2825          2264          2827
BM_knn_search<ArborX::BVH<OpenMP>>/100000/100000/10/1/1/3/manual_time_median                        -0.0007         +0.0046         27245         27227         25317         25434
BM_knn_search<ArborX::BVH<OpenMP>>/1000000/1000000/10/1/1/3/manual_time_median                      -0.0176         -0.0171        406101        398966        343359        337496
BM_knn_search<ArborX::BVH<OpenMP>>/10000/10000/10/0/0/2/manual_time_median                          +0.1855         +0.1855          1606          1903          1607          1906
BM_knn_search<ArborX::BVH<OpenMP>>/100000/100000/10/0/0/2/manual_time_median                        +0.0189         +0.0192         15006         15289         14288         14562
BM_knn_search<ArborX::BVH<OpenMP>>/1000000/1000000/10/0/0/2/manual_time_median                      -0.0001         -0.0001        197239        197218        188066        188041
BM_knn_search<ArborX::BVH<OpenMP>>/10000/10000/10/0/1/3/manual_time_median                          +0.1751         +0.1750          1719          2020          1721          2022
BM_knn_search<ArborX::BVH<OpenMP>>/100000/100000/10/0/1/3/manual_time_median                        +0.0169         +0.0171         20795         21146         20787         21142
BM_knn_search<ArborX::BVH<OpenMP>>/1000000/1000000/10/0/1/3/manual_time_median                      +0.0026         +0.0029        320627        321454        319451        320370
BM_radius_search<ArborX::BVH<OpenMP>>/10000/10000/10/1/0/0/2/manual_time_median                     +0.2125         +0.2124          2103          2551          2105          2553
BM_radius_search<ArborX::BVH<OpenMP>>/100000/100000/10/1/0/0/2/manual_time_median                   +0.0114         +0.0141         18698         18911         18008         18262
BM_radius_search<ArborX::BVH<OpenMP>>/1000000/1000000/10/1/0/0/2/manual_time_median                 -0.0104         -0.0094        187221        185265        184383        182654
BM_radius_search<ArborX::BVH<OpenMP>>/10000/10000/10/1/0/1/3/manual_time_median                     +0.3287         +0.5548          1282          1703           952          1480
BM_radius_search<ArborX::BVH<OpenMP>>/100000/100000/10/1/0/1/3/manual_time_median                   +0.0504         +0.1267          7879          8276          3281          3697
BM_radius_search<ArborX::BVH<OpenMP>>/1000000/1000000/10/1/0/1/3/manual_time_median                 +0.0055         +0.0077         69493         69874         30352         30587
BM_radius_search<ArborX::BVH<OpenMP>>/10000/10000/10/1/10/0/2/manual_time_median                    +0.2293         +0.2292          2219          2728          2221          2730
BM_radius_search<ArborX::BVH<OpenMP>>/100000/100000/10/1/10/0/2/manual_time_median                  +0.0142         +0.0163         19357         19633         18626         18931
BM_radius_search<ArborX::BVH<OpenMP>>/1000000/1000000/10/1/10/0/2/manual_time_median                -0.0101         -0.0107        196025        194040        192991        190930
BM_radius_search<ArborX::BVH<OpenMP>>/10000/10000/10/1/10/1/3/manual_time_median                    +0.3519         +0.5844          1378          1863          1007          1596
BM_radius_search<ArborX::BVH<OpenMP>>/100000/100000/10/1/10/1/3/manual_time_median                  +0.0528         +0.1382          8185          8617          3370          3836
BM_radius_search<ArborX::BVH<OpenMP>>/1000000/1000000/10/1/10/1/3/manual_time_median                +0.0023         +0.0067         72364         72531         31539         31751
BM_radius_search<ArborX::BVH<OpenMP>>/10000/10000/10/0/0/0/2/manual_time_median                     +0.0889         +0.0891          1855          2020          1857          2023
BM_radius_search<ArborX::BVH<OpenMP>>/100000/100000/10/0/0/0/2/manual_time_median                   +0.0075         +0.0076         18640         18781         18641         18781
BM_radius_search<ArborX::BVH<OpenMP>>/1000000/1000000/10/0/0/0/2/manual_time_median                 +0.0016         +0.0031        259042        259467        256014        256818
BM_radius_search<ArborX::BVH<OpenMP>>/10000/10000/10/0/0/1/3/manual_time_median                     +0.2390         +0.2387           701           868           703           871
BM_radius_search<ArborX::BVH<OpenMP>>/100000/100000/10/0/0/1/3/manual_time_median                   +0.0511         +0.0514          3868          4065          3870          4068
BM_radius_search<ArborX::BVH<OpenMP>>/1000000/1000000/10/0/0/1/3/manual_time_median                 +0.0048         +0.0033         29431         29572         28852         28948
BM_radius_search<ArborX::BVH<OpenMP>>/10000/10000/10/0/10/0/2/manual_time_median                    +0.1189         +0.1190          1932          2161          1934          2164
BM_radius_search<ArborX::BVH<OpenMP>>/100000/100000/10/0/10/0/2/manual_time_median                  +0.0128         +0.0127         18840         19080         18841         19080
BM_radius_search<ArborX::BVH<OpenMP>>/1000000/1000000/10/0/10/0/2/manual_time_median                +0.0022         +0.0041        262115        262680        258963        260015
BM_radius_search<ArborX::BVH<OpenMP>>/10000/10000/10/0/10/1/3/manual_time_median                    +0.3029         +0.3025           764           995           766           997
BM_radius_search<ArborX::BVH<OpenMP>>/100000/100000/10/0/10/1/3/manual_time_median                  +0.0673         +0.0673          3988          4256          3989          4258
BM_radius_search<ArborX::BVH<OpenMP>>/1000000/1000000/10/0/10/1/3/manual_time_median                +0.0092         +0.0068         30479         30761         29853         30057
```

## Cuda
```
BM_construction<ArborX::BVH<Cuda>>/10000/0/manual_time_median                                       +0.0049         +0.0048          1398          1405          1413          1420
BM_construction<ArborX::BVH<Cuda>>/100000/0/manual_time_median                                      +0.0062         +0.0052          2136          2149          2526          2540
BM_construction<ArborX::BVH<Cuda>>/1000000/0/manual_time_median                                     -0.0042         +0.0037          6925          6896          7358          7385
BM_construction<ArborX::BVH<Cuda>>/10000/1/manual_time_median                                       +0.0048         +0.0049          1398          1404          1412          1419
BM_construction<ArborX::BVH<Cuda>>/100000/1/manual_time_median                                      +0.0043         +0.0051          2139          2148          2528          2541
BM_construction<ArborX::BVH<Cuda>>/1000000/1/manual_time_median                                     +0.0087         +0.0025          7082          7144          7369          7388
BM_knn_search<ArborX::BVH<Cuda>>/10000/10000/10/1/0/2/manual_time_median                            +0.0125         +0.0116          1553          1573          1646          1665
BM_knn_search<ArborX::BVH<Cuda>>/100000/100000/10/1/0/2/manual_time_median                          +0.0141         +0.0140          6373          6463          6835          6931
BM_knn_search<ArborX::BVH<Cuda>>/1000000/1000000/10/1/0/2/manual_time_median                        +0.0081         +0.0048         26673         26891         27521         27654
BM_knn_search<ArborX::BVH<Cuda>>/10000/10000/10/1/1/3/manual_time_median                            +0.0137         +0.0127          1599          1621          1691          1712
BM_knn_search<ArborX::BVH<Cuda>>/100000/100000/10/1/1/3/manual_time_median                          -0.0032         +0.0040          7256          7233          7662          7692
BM_knn_search<ArborX::BVH<Cuda>>/1000000/1000000/10/1/1/3/manual_time_median                        +0.0025         +0.0022         43604         43712         44458         44554
BM_knn_search<ArborX::BVH<Cuda>>/10000/10000/10/0/0/2/manual_time_median                            +0.0330         +0.0307          1163          1201          1254          1293
BM_knn_search<ArborX::BVH<Cuda>>/100000/100000/10/0/0/2/manual_time_median                          +0.0098         +0.0059          4657          4703          5091          5121
BM_knn_search<ArborX::BVH<Cuda>>/1000000/1000000/10/0/0/2/manual_time_median                        +0.0217         +0.0115         56585         57813         57235         57891
BM_knn_search<ArborX::BVH<Cuda>>/10000/10000/10/0/1/3/manual_time_median                            +0.0289         +0.0265          1220          1256          1311          1346
BM_knn_search<ArborX::BVH<Cuda>>/100000/100000/10/0/1/3/manual_time_median                          +0.0037         +0.0062          6753          6778          7192          7237
BM_knn_search<ArborX::BVH<Cuda>>/1000000/1000000/10/0/1/3/manual_time_median                        -0.0059         -0.0058        100454         99864        101345        100758
BM_radius_search<ArborX::BVH<Cuda>>/10000/10000/10/1/0/0/2/manual_time_median                       -0.1380         -0.1285          1134           978          1227          1069
BM_radius_search<ArborX::BVH<Cuda>>/100000/100000/10/1/0/0/2/manual_time_median                     -0.0486         -0.0462          3371          3207          3830          3653
BM_radius_search<ArborX::BVH<Cuda>>/1000000/1000000/10/1/0/0/2/manual_time_median                   -0.0111         -0.0085         17116         16926         17970         17817
BM_radius_search<ArborX::BVH<Cuda>>/10000/10000/10/1/0/1/3/manual_time_median                       -0.1505         -0.1393          1070           909          1162          1001
BM_radius_search<ArborX::BVH<Cuda>>/100000/100000/10/1/0/1/3/manual_time_median                     -0.0583         -0.0489          2621          2468          3082          2931
BM_radius_search<ArborX::BVH<Cuda>>/1000000/1000000/10/1/0/1/3/manual_time_median                   -0.0239         -0.0160          7944          7755          8720          8581
BM_radius_search<ArborX::BVH<Cuda>>/10000/10000/10/1/10/0/2/manual_time_median                      -0.1103         -0.1031          1232          1096          1324          1188
BM_radius_search<ArborX::BVH<Cuda>>/100000/100000/10/1/10/0/2/manual_time_median                    -0.0279         -0.0237          4331          4210          4797          4684
BM_radius_search<ArborX::BVH<Cuda>>/1000000/1000000/10/1/10/0/2/manual_time_median                  +0.0020         -0.0019         24435         24483         25320         25272
BM_radius_search<ArborX::BVH<Cuda>>/10000/10000/10/1/10/1/3/manual_time_median                      -0.1044         -0.0969          1137          1019          1230          1111
BM_radius_search<ArborX::BVH<Cuda>>/100000/100000/10/1/10/1/3/manual_time_median                    -0.0146         -0.0221          3783          3728          4244          4150
BM_radius_search<ArborX::BVH<Cuda>>/1000000/1000000/10/1/10/1/3/manual_time_median                  -0.0073         -0.0065          9960          9888         10799         10729
BM_radius_search<ArborX::BVH<Cuda>>/10000/10000/10/0/0/0/2/manual_time_median                       -0.1861         -0.1685           852           693           944           785
BM_radius_search<ArborX::BVH<Cuda>>/100000/100000/10/0/0/0/2/manual_time_median                     -0.0715         -0.0558          2224          2065          2688          2538
BM_radius_search<ArborX::BVH<Cuda>>/1000000/1000000/10/0/0/0/2/manual_time_median                   +0.0092         +0.0099         64139         64732         64993         65634
BM_radius_search<ArborX::BVH<Cuda>>/10000/10000/10/0/0/1/3/manual_time_median                       -0.2085         -0.1858           756           599           848           691
BM_radius_search<ArborX::BVH<Cuda>>/100000/100000/10/0/0/1/3/manual_time_median                     -0.1077         -0.0788          1482          1322          1941          1788
BM_radius_search<ArborX::BVH<Cuda>>/1000000/1000000/10/0/0/1/3/manual_time_median                   -0.0343         -0.0262          5149          4972          5968          5812
BM_radius_search<ArborX::BVH<Cuda>>/10000/10000/10/0/10/0/2/manual_time_median                      -0.1246         -0.1128           859           752           950           842
BM_radius_search<ArborX::BVH<Cuda>>/100000/100000/10/0/10/0/2/manual_time_median                    -0.0329         -0.0274          3252          3145          3720          3618
BM_radius_search<ArborX::BVH<Cuda>>/1000000/1000000/10/0/10/0/2/manual_time_median                  +0.0132         +0.0124         72725         73682         73583         74493
BM_radius_search<ArborX::BVH<Cuda>>/10000/10000/10/0/10/1/3/manual_time_median                      -0.1322         -0.1190           825           716           917           808
BM_radius_search<ArborX::BVH<Cuda>>/100000/100000/10/0/10/1/3/manual_time_median                    -0.0398         -0.0330          2488          2389          2950          2852
BM_radius_search<ArborX::BVH<Cuda>>/1000000/1000000/10/0/10/1/3/manual_time_median                  +0.0026         -0.0112          7157          7175          7886          7798
```
